/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SincronizacaoRouteImport } from './routes/sincronizacao'
import { Route as LicitacoesIndexRouteImport } from './routes/licitacoes.index'
import { Route as LicitacoesIdRouteImport } from './routes/licitacoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SincronizacaoRoute = SincronizacaoRouteImport.update({
  id: '/sincronizacao',
  path: '/sincronizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIndexRoute = LicitacoesIndexRouteImport.update({
  id: '/licitacoes/',
  path: '/licitacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIdRoute = LicitacoesIdRouteImport.update({
  id: '/licitacoes/$id',
  path: '/licitacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes': typeof LicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sincronizacao': typeof SincronizacaoRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sincronizacao' | '/licitacoes/$id' | '/licitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sincronizacao' | '/licitacoes/$id' | '/licitacoes'
  id: '__root__' | '/' | '/sincronizacao' | '/licitacoes/$id' | '/licitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SincronizacaoRoute: typeof SincronizacaoRoute
  LicitacoesIdRoute: typeof LicitacoesIdRoute
  LicitacoesIndexRoute: typeof LicitacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sincronizacao': {
      id: '/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof SincronizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/': {
      id: '/licitacoes/'
      path: '/licitacoes'
      fullPath: '/licitacoes/'
      preLoaderRoute: typeof LicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/$id': {
      id: '/licitacoes/$id'
      path: '/licitacoes/$id'
      fullPath: '/licitacoes/$id'
      preLoaderRoute: typeof LicitacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SincronizacaoRoute: SincronizacaoRoute,
  LicitacoesIdRoute: LicitacoesIdRoute,
  LicitacoesIndexRoute: LicitacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
